###
GET http://localhost:5000/api/grade-schema/12

###
GET http://localhost:5000/api/grade-schema

###
GET http://localhost:5000/api/students

###
GET http://localhost:5000/api/students/stream

###
POST http://localhost:5000/api/report
Content-Type: application/json

###
POST http://localhost:5000/api/report/all
Content-Type: application/json

###
GET http://localhost:5000/api/data-generator

###
GET http://localhost:5000/test